name: wx3_interface
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  percent_indicator: ^4.2.2
  geolocator: ^10.1.0
  geocoding: ^2.2.0
  google_fonts: ^6.1.0
  google_maps_flutter: ^2.5.0
  font_awesome_flutter: ^10.7.0
  flutter_animate: ^4.2.0
  lottie: ^2.6.0
  cupertino_icons: ^1.0.8
  provider: ^6.0.5
  firebase_core: ^2.28.0
  firebase_auth: ^4.18.3
  firebase_database: ^10.4.3
  cloud_firestore: ^4.15.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0



flutter:
  uses-material-design: true
  assets:
    - assets/lottie/
    - lib/assets/lottie/
