// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_tYm2GrcieFD94NwoIJtAyervGzIMgbw',
    appId: '1:73275892816:web:8912965c0f4223fb151d55',
    messagingSenderId: '73275892816',
    projectId: 'defensesuit',
    authDomain: 'defensesuit.firebaseapp.com',
    storageBucket: 'defensesuit.firebasestorage.app',
    measurementId: 'G-V3KYYM36ED',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCa3d0tsP34PRW2EHBm0iGFHjOFPOL2ZeA',
    appId: '1:73275892816:android:3b9ad5b23858853d151d55',
    messagingSenderId: '73275892816',
    projectId: 'defensesuit',
    storageBucket: 'defensesuit.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKHZqdhHvwjV9RvtEAbSAa82IMDLC-GJY',
    appId: '1:73275892816:ios:601d388add74cc65151d55',
    messagingSenderId: '73275892816',
    projectId: 'defensesuit',
    storageBucket: 'defensesuit.firebasestorage.app',
    iosBundleId: 'com.example.wx3Interface',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKHZqdhHvwjV9RvtEAbSAa82IMDLC-GJY',
    appId: '1:73275892816:ios:601d388add74cc65151d55',
    messagingSenderId: '73275892816',
    projectId: 'defensesuit',
    storageBucket: 'defensesuit.firebasestorage.app',
    iosBundleId: 'com.example.wx3Interface',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_tYm2GrcieFD94NwoIJtAyervGzIMgbw',
    appId: '1:73275892816:web:3417b5598d648e32151d55',
    messagingSenderId: '73275892816',
    projectId: 'defensesuit',
    authDomain: 'defensesuit.firebaseapp.com',
    storageBucket: 'defensesuit.firebasestorage.app',
    measurementId: 'G-WVMPSR4HGG',
  );
}
